### ISSUE TITLE
hp的监控工具有 centos7 x64的安装包没 ?

### ISSUE THREAD

**Issue by nondevops** [zhangrj/check_hpasm-hpasm-hphealth#1]
hp的监控工具有 centos7 x64的安装包没 ?

**Comment by zhangrj** [comment]
在这里搜一下，有可能有，https://support.hpe.com/hpsc/swd/public/detail?swItemId=MTX_f9f4fbfb27954008b6f4d7f848#tab3

**Comment by zhangrj** [comment]
> hp的监控工具有 centos7 x64的安装包没 ?

在这里搜一下，有可能有，https://support.hpe.com/hpsc/swd/public/detail?swItemId=MTX_f9f4fbfb27954008b6f4d7f848#tab3
